// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK2UQQoSCfJ-WFs0x-9pf-D_bDiB3ta5A',
    appId: '1:857911585291:web:8ce2f3af77d61d15ae350e',
    messagingSenderId: '857911585291',
    projectId: 'liberresapplication',
    authDomain: 'liberresapplication.firebaseapp.com',
    storageBucket: 'liberresapplication.firebasestorage.app',
    measurementId: 'G-WD4VHVGWRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwEGdJxmvUvXZN8tV59uU9lZVRCRK0a4E',
    appId: '1:857911585291:android:da20a8c15264ac8dae350e',
    messagingSenderId: '857911585291',
    projectId: 'liberresapplication',
    storageBucket: 'liberresapplication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNuJwSepfYt4tSX4vtDMgNiElLz5i0AbI',
    appId: '1:857911585291:ios:45e2343753782f3dae350e',
    messagingSenderId: '857911585291',
    projectId: 'liberresapplication',
    storageBucket: 'liberresapplication.firebasestorage.app',
    iosBundleId: 'com.example.liberres',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNuJwSepfYt4tSX4vtDMgNiElLz5i0AbI',
    appId: '1:857911585291:ios:45e2343753782f3dae350e',
    messagingSenderId: '857911585291',
    projectId: 'liberresapplication',
    storageBucket: 'liberresapplication.firebasestorage.app',
    iosBundleId: 'com.example.liberres',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK2UQQoSCfJ-WFs0x-9pf-D_bDiB3ta5A',
    appId: '1:857911585291:web:255ecafcd35a48b7ae350e',
    messagingSenderId: '857911585291',
    projectId: 'liberresapplication',
    authDomain: 'liberresapplication.firebaseapp.com',
    storageBucket: 'liberresapplication.firebasestorage.app',
    measurementId: 'G-BZ9JFX53JG',
  );

}